sudo: required
services:
- docker
env:
  global:
    # Ensure the downloaded SDK is first on the PATH
    - PATH=${HOME}/google-cloud-sdk/bin:$PATH
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_7b0fcf26d23d_key -iv $encrypted_7b0fcf26d23d_iv -in credentials.tar.enc -out credentials.tar -d
- tar -xvf credentials.tar
- rm credentials.tar
- rm gc_cred.json
- mkdir config
- mv smtp.json config/smtp.json
- docker run --name mongo -p 27017:27017 -d mongo:3.2 
- docker run --name redis -p 6379:6379 -d redis:3.0 
- sleep 30s
- docker exec $(docker ps -aqf "name=mongo") mongo _GLOBAL --eval "db.getCollection('_Settings').insertOne({secureKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',clusterKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',myURL:'http://localhost:4730'});"
- git clone https://github.com/cloudboost/javascriptsdk
- npm install grunt-cli -g
install:
- cd javascriptsdk
- npm install
- grunt
- cd ..
- docker build -t cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/cloudboost:latest .
- docker run --name cloudboost -p 4730:4730 -it --link redis:redis --link mongo:mongo -d cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER 
- sleep 30s
- cd javascriptsdk
- npm test
- cd ..
after_success:
#Deploy. 
#Docker Login
- openssl aes-256-cbc -K $encrypted_7b0fcf26d23d_key -iv $encrypted_7b0fcf26d23d_iv -in credentials.tar.enc -out credentials.tar -d
- tar -xvf credentials.tar
- docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL
# Make sure SDK is downloaded - cache once it's working
- curl https://sdk.cloud.google.com | bash;
# List the SDK contents to ensure it's downloaded
- ls -l ${HOME}/google-cloud-sdk/bin
# Ensure the correct gcloud is being used
- which gcloud
# Print the gcloud version and make sure it's something
- gcloud --version
- ls
#Activate Google Cloud SDK with your project
- gcloud auth activate-service-account --key-file gc_cred.json
#Install Kubectl
- gcloud components install kubectl
- gcloud container clusters get-credentials $GOOGLECLUSTERNAME --zone $GOOGLEZONE --project $GOOGLEPROJECT
#Push docker images. 
- docker push cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER
- docker push cloudboost/cloudboost:latest
#Upload to Kubernetes for deployment.
- kubectl rolling-update cloudboost-engine --image=cloudboost/cloudboost:latest --image-pull-policy=Always 
#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW

